DROP DATABASE IF EXISTS my_PERSONNEL;
CREATE DATABASE my_personnel;

USE my_personnel;

CREATE TABLE DEPT(
  DEPTNO INT(2) NOT NULL,
  DNAME VARCHAR(14),
  LOC VARCHAR(14),
  PRIMARY KEY(DEPTNO));

CREATE TABLE EMP(
  EMPNO INT(4) NOT NULL,
  ENAME VARCHAR(10), JOB VARCHAR(25),
  HIREDATE DATE,
  MGR INT(4),
  SAL FLOAT(7,2),
  COMM FLOAT(7,2),
  DEPTNO INT(2),
  PRIMARY KEY(EMPNO),
  FOREIGN KEY(DEPTNO) REFERENCES DEPT(DEPTNO));



SHOW TABLES;

INSERT INTO DEPT(DEPTNO, DNAME, LOC)
 VALUES (10, 'ACCOUNTING', 'NEW YORK');
INSERT INTO DEPT(DEPTNO, DNAME, LOC)
 VALUES (20, 'RESEARCH', 'DALLAS');
INSERT INTO DEPT(DEPTNO, DNAME, LOC)
 VALUES (30, 'SALES', 'CHICAGO');
INSERT INTO DEPT(DEPTNO, DNAME, LOC)
 VALUES (40, 'OPERATIONS', 'BOSTON');

INSERT INTO EMP
 VALUES (10, 'CODD', 'ANALYST', '1989/01/01', 15, 3000, NULL, 10);
INSERT INTO EMP
 VALUES (15, 'ELMASRI', 'ANALYST', '1995/05/02', 15, 1200, 150, 10);
INSERT INTO EMP
 VALUES (20, 'NAVATHE', 'SALESMAN', '1977/07/07', 20, 2000, NULL, 20);
INSERT INTO EMP
 VALUES (30, 'DATE', 'PROGRAMMER', '2004/05/04', 15, 1800, 200, 10);


SELECT * FROM EMP;
SELECT * FROM DEPT;